[wandb]
project_name = "GTNO"
run_name = "Test"

[dataset]
molecule_type = "aspirin"

[training]
seed = 42
batch_size = 128
epochs = 100
max_grad_norm = 1.0

[optimizer]
type = "adamw"
learning_rate = 1e-4
weight_decay = 1e-5
adam_betas = [0.9, 0.999]
adam_eps = 1e-10

[scheduler]
type = "cosine_warmup"
step_size = 10
gamma = 0.1

[model]
model_type = "gtno"
lifting_dim = 128
norm = "rms"
activation = "silu"
num_layers = 5
num_heads = 4
graph_attention_type = "unified_mha"
heterogenous_attention_type = "ghcna"
num_timesteps = 8
