[wandb]
project_name = "GTNO"

[benchmark]
runs = 3
compile = true

[training]
seed = 42
batch_size = 128
epochs = 1000
max_grad_norm = 1.0

[optimizer]
type = "adamw"
learning_rate = 1e-4
weight_decay = 1e-5
adam_betas = [0.9, 0.999]
adam_eps = 1e-10

[scheduler]
type = "cosine_annealing"

[model]
model_type = "gtno"
lifting_dim = 128
num_timesteps = 8
norm = "rms"
activation = "silu"
heterogenous_attention_type = "GHCA"
use_rope = true
use_spherical_harmonics = false
value_residual_type = "learnable"
use_equivariant_lifting = true
num_layers = 5
num_heads = 4
