[wandb]
project_name = "GTNO"
run_name = "Test"

[training]
seed = 42
batch_size = 1
learning_rate = 0.001
epochs = 100
max_grad_norm = 1.0

[optimizer]
type = "adamw"
learning_rate = 0.001
weight_decay = 0.0001
adam_betas = [0.9, 0.999]

[scheduler]
type = "step"
step_size = 10
gamma = 0.1

[model]
model_type = "egno"
lifting_dim = 128
norm = "rms"
activation = "relu"
num_layers = 3
num_heads = 4
graph_attention_type = "unified_mha"
heterogenous_attention_type = "ghcna"
num_timesteps = 8
