[wandb]
use_wandb = false

[benchmark]
runs = 1
compile = true
molecule_type = "toluene"
md17_version = "rmd17"
delta_T = 3000
# delta_T = 30000

[training]
seed = 42
batch_size = 100
epochs = 1000
max_grad_norm = 1.0
learnable_noise_std = false
brownian_noise_std = 0.1

[dataloader]
persistent_workers = true
num_workers = 4
pin_memory = true

[optimizer]
type = "adamw"
learning_rate = 1e-3
weight_decay = 1e-5
adam_betas = [0.9, 0.999]
adam_eps = 1e-10

[scheduler]
type = "none"

[model]
model_type = "gtno"
lifting_dim = 128
num_timesteps = 8
norm = "rms"
activation = "swiglu"
heterogenous_attention_type = "GHCA"
use_rope = true
use_spherical_harmonics = false
value_residual_type = "learnable"
use_equivariant_lifting = true
num_layers = 5
num_heads = 8
