[wandb]
use_wandb = false

[benchmark]
runs = 2
compile = true
# multitask = false
# molecule_type = "aspirin"
log_weights = false

[dataloader]
multitask = true
delta_T = 3000
# Single-task dataloader parameters
md17_version = "md17"
molecule_type = "aspirin"  # Iterates through single-task learning on these molecules

# Multitask dataloader parameters
train_molecules = ["aspirin", "benzene", "ethanol", "toluene", "uracil", "salicylic"]
validation_molecules = ["malonaldehyde"]
test_molecules = ["naphthalene"]

# Other dataloader parameters
explicit_hydrogen = false
explicit_hydrogen_gradients = false
rrwp_length = 8  # 0 for no RRWPs
persistent_workers = true
num_workers = 4
pin_memory = true
force_regenerate = true

[training]
device = "cuda"
seed = 42
batch_size = 100
epochs = 1000
max_grad_norm = 1.0
learnable_noise_std = true
brownian_noise_std = 0.1

[optimizer]
type = "adamw"
learning_rate = 1e-3
weight_decay = 1e-5
adam_betas = [0.9, 0.999]
adam_eps = 1e-10

[scheduler]
type = "none"

[model]
model_type = "GTNO"
# Architecture parameters
num_layers = 5
num_heads = 8
lifting_dim = 128
num_timesteps = 8
# Attention parameters
heterogenous_attention_type = "GHCA"
use_rope = true
learnable_attention_denom = false
# Feature parameters
use_spherical_harmonics = false
use_equivariant_lifting = true
# Layer parameters
norm = "rms"
activation = "swiglu"
value_residual_type = "learnable"