[project]
name = "ATOM"
version = "0.1.3"
description = ""
authors = [{ name = "Anonymized for review" }]
requires-python = ">=3.11"
readme = "README.md"
keywords = [
    "graph transformer",
    "quantum chemistry",
    "molecular dynamics",
    "neural operator",
]
dependencies = [
    "numpy>=2.0.0,<3",
    "scipy>=1.14.0,<2",
    "pandas>=2.1.0,<3",
    "torch>=2.7.1,<3",
    "e3nn>=0.5.4,<0.6",
    "tensordict>=0.7.0,<1.0",
    "pytorch_optimizer>=3.8.0,<4",
    "pydantic>=2.10.6,<3",
    "wandb==0.18.3",
    "tqdm>=4.67.1,<5",
    "torchvision>=0.22.1,<0.23",
    "torchaudio>=2.7.1,<3",
    "matplotlib>=3.8.0,<4",
    "usyd-colors>=0.1.0,<0.2",
    "rdkit>=2024.9.6,<2025",
    "umap-learn>=0.5.6,<1",
    "numba>=0.60,<1",
    "llvmlite>=0.43,<1",
    "scikit-learn>=1.5.0,<2",
    "optuna>=3.6.1,<4",
    "optuna-dashboard>=0.19.0",
    "dscribe>=2.1.1",
]

[project.scripts]
train = "atom.train:main"
inference = "atom.inference:main"
equivariance = "atom.cli.equivariance:main"
optimize = "atom.optimize:main"
tables = "Z_paper_content.run_tables:main"
p_invariance = "Z_paper_content.invariances:main_p"
t_invariance = "Z_paper_content.invariances:main_t"

[dependency-groups]
dev = [
    "pytest>=8.3.4,<9",
    "types-tqdm>=4.67.0.20241119,<5",
    "pandas-stubs>=2.2.3.241126,<3",
]

[tool.uv]

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-gpu" }
torchvision = { index = "pytorch-gpu" }
torchaudio = { index = "pytorch-gpu" }

[tool.hatch.build.targets.sdist]
include = ["src/atom", "Z_paper_content"]

[tool.hatch.build.targets.wheel]
include = ["src/atom", "Z_paper_content"]

[tool.hatch.build.targets.wheel.sources]
"src/atom" = "atom"
"Z_paper_content" = "Z_paper_content"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 150
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__", "*/.mypy_cache", "**/.pytest_cache"]
venvPath = "."
venv = ".venv"
useLibraryCodeForTypes = true
reportMissingImports = true
reportMissingTypeStubs = false
